server:
  port: 8081

topic:
  name: Word

spring:
  kafka:
    consumer:
      group-id: "default"

  liquibase:
    change-log: classpath:liquibase.xml
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver